<?xml version="1.0" encoding="UTF-8"?>
<package uri="platform/core/api/bluetooth">
	<error name="BT_ERROR_NOT_INITIALIZED">
		<value>TIZEN_ERROR_BLUETOOTH | 0x0101</value>
		<msg>Local adapter not initialized</msg>
	</error>
	<error name="BT_ERROR_NOT_ENABLED">
		<value>TIZEN_ERROR_BLUETOOTH | 0x0102</value>
		<msg>Local adapter not enabled</msg>
	</error>
	<error name="BT_ERROR_ALREADY_DONE">
		<value>TIZEN_ERROR_BLUETOOTH | 0x0103</value>
		<msg>Operation already done</msg>
	</error>
	<error name="BT_ERROR_OPERATION_FAILED">
		<value>TIZEN_ERROR_BLUETOOTH | 0x0104</value>
		<msg>Operation failed</msg>
	</error>
	<error name="BT_ERROR_NOT_IN_PROGRESS">
		<value>TIZEN_ERROR_BLUETOOTH | 0x0105</value>
		<msg>Operation not in progress</msg>
	</error>
	<error name="BT_ERROR_REMOTE_DEVICE_NOT_BONDED">
		<value>TIZEN_ERROR_BLUETOOTH | 0x0106</value>
		<msg>Remote device not bonde</msg>
	</error>
	<error name="BT_ERROR_AUTH_REJECTED">
		<value>TIZEN_ERROR_BLUETOOTH | 0x0107</value>
		<msg>Authentication rejected</msg>
	</error>
	<error name="BT_ERROR_AUTH_FAILED">
		<value>TIZEN_ERROR_BLUETOOTH | 0x0108</value>
		<msg>Authentication failed</msg>
	</error>
	<error name="BT_ERROR_REMOTE_DEVICE_NOT_FOUND">
		<value>TIZEN_ERROR_BLUETOOTH | 0x0109</value>
		<msg>Remote device not found </msg>
	</error>
	<error name="BT_ERROR_SERVICE_SEARCH_FAILED">
		<value>TIZEN_ERROR_BLUETOOTH | 0x010A</value>
		<msg>Service search failed</msg>
	</error>
	<error name="BT_ERROR_REMOTE_DEVICE_NOT_CONNECTED">
		<value>TIZEN_ERROR_BLUETOOTH | 0x010B</value>
		<msg>Remote device is not connected</msg>
	</error>
	<error name="BT_ERROR_AGAIN">
		<value>TIZEN_ERROR_BLUETOOTH | 0x010C</value>
		<msg>Resource temporarily unavailable </msg>
	</error>
	<error name="BT_ERROR_SERVICE_NOT_FOUND">
		<value>TIZEN_ERROR_BLUETOOTH | 0x010D</value>
		<msg>Service not found</msg>
	</error>
</package>

